"""Generate registry/servers/<id>.yaml for the entire 171-server catalogue.

Run once from the repo root:
    uv run python scripts/build_registry.py
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "registry" / "servers"


@dataclass
class Entry:
    id: str
    name: str
    category: str
    description: str
    auth_type: str = "none"
    auth_env: list[str] = field(default_factory=list)
    tools: list[str] = field(default_factory=list)
    docs: str = ""
    status: str = "planned"


# --- CATALOGUE (171 entries) ---------------------------------------------------

CATALOGUE: list[Entry] = [
    # === Development / Version Control (10) ===
    Entry(
        "github",
        "GitHub",
        "development",
        "GitHub REST + GraphQL API",
        "bearer_token",
        ["GITHUB_TOKEN"],
        [
            "list_repos",
            "get_repo",
            "list_issues",
            "create_issue",
            "list_pulls",
            "get_pr",
            "list_commits",
        ],
        "https://docs.github.com/en/rest",
        "pilot",
    ),
    Entry(
        "gitlab",
        "GitLab",
        "development",
        "GitLab REST API",
        "bearer_token",
        ["GITLAB_TOKEN"],
        ["list_projects", "get_project", "list_issues", "create_issue", "list_merge_requests"],
        "https://docs.gitlab.com/ee/api/",
    ),
    Entry(
        "bitbucket",
        "Bitbucket",
        "development",
        "Bitbucket Cloud API",
        "basic",
        ["BITBUCKET_USERNAME", "BITBUCKET_APP_PASSWORD"],
        ["list_repos", "get_repo", "list_pull_requests"],
        "https://developer.atlassian.com/cloud/bitbucket/rest/",
    ),
    Entry(
        "gitea",
        "Gitea",
        "development",
        "Self-hosted Gitea API",
        "bearer_token",
        ["GITEA_TOKEN", "GITEA_URL"],
        ["list_repos", "get_repo", "list_issues"],
        "https://docs.gitea.com/api/",
    ),
    Entry(
        "git-local",
        "Git (local)",
        "development",
        "Local git repository operations",
        "none",
        [],
        ["status", "log", "diff", "blame", "show", "branches"],
        "https://git-scm.com/docs",
    ),
    Entry(
        "gerrit",
        "Gerrit",
        "development",
        "Gerrit code review API",
        "basic",
        ["GERRIT_USER", "GERRIT_PASSWORD", "GERRIT_URL"],
        ["list_changes", "get_change", "list_reviewers"],
        "https://gerrit-review.googlesource.com/Documentation/rest-api.html",
    ),
    Entry(
        "codeberg",
        "Codeberg",
        "development",
        "Codeberg (Gitea-based) API",
        "bearer_token",
        ["CODEBERG_TOKEN"],
        ["list_repos", "list_issues"],
        "https://codeberg.org/api/swagger",
    ),
    Entry(
        "azure-devops",
        "Azure DevOps",
        "development",
        "Azure DevOps REST API",
        "bearer_token",
        ["AZURE_DEVOPS_PAT", "AZURE_DEVOPS_ORG"],
        ["list_projects", "list_repos", "list_work_items", "create_work_item"],
        "https://learn.microsoft.com/en-us/rest/api/azure/devops/",
    ),
    Entry(
        "sourcegraph",
        "Sourcegraph",
        "development",
        "Code search via Sourcegraph",
        "bearer_token",
        ["SOURCEGRAPH_TOKEN", "SOURCEGRAPH_URL"],
        ["search_code", "get_file"],
        "https://sourcegraph.com/docs/api/graphql",
    ),
    Entry(
        "codecov",
        "Codecov",
        "development",
        "Codecov coverage reports",
        "bearer_token",
        ["CODECOV_TOKEN"],
        ["get_coverage", "list_reports"],
        "https://docs.codecov.com/reference",
    ),
    # === Databases (20) ===
    Entry(
        "postgres",
        "PostgreSQL",
        "database",
        "PostgreSQL query + schema access",
        "custom",
        ["POSTGRES_DSN"],
        ["query", "list_tables", "describe_table", "list_schemas"],
        "https://www.postgresql.org/docs/current/",
        "pilot",
    ),
    Entry(
        "mysql",
        "MySQL",
        "database",
        "MySQL query + schema access",
        "custom",
        ["MYSQL_DSN"],
        ["query", "list_tables", "describe_table"],
        "https://dev.mysql.com/doc/",
    ),
    Entry(
        "mariadb",
        "MariaDB",
        "database",
        "MariaDB query access",
        "custom",
        ["MARIADB_DSN"],
        ["query", "list_tables"],
        "https://mariadb.com/kb/en/documentation/",
    ),
    Entry(
        "sqlite",
        "SQLite",
        "database",
        "SQLite file query access",
        "none",
        ["SQLITE_PATH"],
        ["query", "list_tables", "describe_table"],
        "https://www.sqlite.org/docs.html",
    ),
    Entry(
        "mongodb",
        "MongoDB",
        "database",
        "MongoDB document operations",
        "custom",
        ["MONGODB_URI"],
        ["find", "insert", "update", "delete", "list_collections"],
        "https://www.mongodb.com/docs/manual/",
    ),
    Entry(
        "redis",
        "Redis",
        "database",
        "Redis key-value + pub/sub",
        "custom",
        ["REDIS_URL"],
        ["get", "set", "delete", "keys", "hget", "hset"],
        "https://redis.io/docs/",
    ),
    Entry(
        "elasticsearch",
        "Elasticsearch",
        "database",
        "Elasticsearch search + index",
        "custom",
        ["ELASTICSEARCH_URL", "ELASTICSEARCH_API_KEY"],
        ["search", "index_doc", "list_indices"],
        "https://www.elastic.co/guide/en/elasticsearch/reference/current/",
    ),
    Entry(
        "opensearch",
        "OpenSearch",
        "database",
        "OpenSearch search + index",
        "custom",
        ["OPENSEARCH_URL"],
        ["search", "index_doc", "list_indices"],
        "https://opensearch.org/docs/latest/",
    ),
    Entry(
        "cassandra",
        "Cassandra",
        "database",
        "Cassandra CQL access",
        "custom",
        ["CASSANDRA_CONTACT_POINTS", "CASSANDRA_USER", "CASSANDRA_PASSWORD"],
        ["query", "list_keyspaces", "list_tables"],
        "https://cassandra.apache.org/doc/",
    ),
    Entry(
        "clickhouse",
        "ClickHouse",
        "database",
        "ClickHouse analytical queries",
        "custom",
        ["CLICKHOUSE_URL"],
        ["query", "list_tables"],
        "https://clickhouse.com/docs",
    ),
    Entry(
        "duckdb",
        "DuckDB",
        "database",
        "In-process DuckDB queries",
        "none",
        ["DUCKDB_PATH"],
        ["query", "list_tables"],
        "https://duckdb.org/docs/",
    ),
    Entry(
        "cockroachdb",
        "CockroachDB",
        "database",
        "CockroachDB distributed SQL",
        "custom",
        ["COCKROACH_DSN"],
        ["query", "list_tables"],
        "https://www.cockroachlabs.com/docs/",
    ),
    Entry(
        "neo4j",
        "Neo4j",
        "database",
        "Neo4j graph queries via Cypher",
        "custom",
        ["NEO4J_URI", "NEO4J_USER", "NEO4J_PASSWORD"],
        ["cypher", "list_labels", "list_relationships"],
        "https://neo4j.com/docs/",
    ),
    Entry(
        "dynamodb",
        "DynamoDB",
        "database",
        "AWS DynamoDB item operations",
        "aws_sig",
        ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
        ["get_item", "put_item", "query", "scan", "list_tables"],
        "https://docs.aws.amazon.com/amazondynamodb/",
    ),
    Entry(
        "cosmosdb",
        "Azure Cosmos DB",
        "database",
        "Cosmos DB SQL API",
        "custom",
        ["COSMOS_ENDPOINT", "COSMOS_KEY"],
        ["query", "read_item", "upsert_item"],
        "https://learn.microsoft.com/en-us/azure/cosmos-db/",
    ),
    Entry(
        "firestore",
        "Firestore",
        "database",
        "Google Cloud Firestore",
        "gcp_sa",
        ["GOOGLE_APPLICATION_CREDENTIALS", "GCP_PROJECT"],
        ["get_document", "set_document", "query_collection"],
        "https://cloud.google.com/firestore/docs",
    ),
    Entry(
        "supabase",
        "Supabase",
        "database",
        "Supabase Postgres + PostgREST",
        "bearer_token",
        ["SUPABASE_URL", "SUPABASE_KEY"],
        ["query_table", "insert", "update", "delete"],
        "https://supabase.com/docs",
    ),
    Entry(
        "planetscale",
        "PlanetScale",
        "database",
        "PlanetScale serverless MySQL",
        "bearer_token",
        ["PLANETSCALE_TOKEN", "PLANETSCALE_ORG"],
        ["list_databases", "list_branches", "query"],
        "https://planetscale.com/docs/reference",
    ),
    Entry(
        "surrealdb",
        "SurrealDB",
        "database",
        "SurrealDB multi-model",
        "custom",
        ["SURREAL_URL", "SURREAL_USER", "SURREAL_PASS"],
        ["query"],
        "https://surrealdb.com/docs",
    ),
    Entry(
        "influxdb",
        "InfluxDB",
        "database",
        "InfluxDB time-series",
        "bearer_token",
        ["INFLUX_URL", "INFLUX_TOKEN", "INFLUX_ORG"],
        ["query_flux", "write_points"],
        "https://docs.influxdata.com/",
    ),
    # === Cloud Platforms (15) ===
    Entry(
        "aws",
        "AWS",
        "cloud",
        "AWS multi-service (S3, EC2, Lambda, IAM)",
        "aws_sig",
        ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
        ["list_s3_buckets", "list_ec2_instances", "invoke_lambda", "list_iam_users"],
        "https://docs.aws.amazon.com/",
    ),
    Entry(
        "gcp",
        "Google Cloud",
        "cloud",
        "GCP multi-service",
        "gcp_sa",
        ["GOOGLE_APPLICATION_CREDENTIALS", "GCP_PROJECT"],
        ["list_gcs_buckets", "list_compute_instances"],
        "https://cloud.google.com/docs",
    ),
    Entry(
        "azure",
        "Azure",
        "cloud",
        "Azure multi-service",
        "custom",
        ["AZURE_SUBSCRIPTION_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID"],
        ["list_resource_groups", "list_vms"],
        "https://learn.microsoft.com/en-us/azure/",
    ),
    Entry(
        "cloudflare",
        "Cloudflare",
        "cloud",
        "Cloudflare API (DNS, Workers, R2)",
        "bearer_token",
        ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"],
        ["list_zones", "list_dns_records", "list_workers"],
        "https://developers.cloudflare.com/api/",
    ),
    Entry(
        "digitalocean",
        "DigitalOcean",
        "cloud",
        "DigitalOcean API",
        "bearer_token",
        ["DIGITALOCEAN_TOKEN"],
        ["list_droplets", "list_apps", "list_databases"],
        "https://docs.digitalocean.com/reference/api/",
    ),
    Entry(
        "linode",
        "Linode",
        "cloud",
        "Linode/Akamai API",
        "bearer_token",
        ["LINODE_TOKEN"],
        ["list_instances", "list_volumes"],
        "https://www.linode.com/docs/api/",
    ),
    Entry(
        "hetzner",
        "Hetzner Cloud",
        "cloud",
        "Hetzner Cloud API",
        "bearer_token",
        ["HETZNER_TOKEN"],
        ["list_servers", "list_volumes"],
        "https://docs.hetzner.cloud/",
    ),
    Entry(
        "vercel",
        "Vercel",
        "cloud",
        "Vercel deployments + projects",
        "bearer_token",
        ["VERCEL_TOKEN"],
        ["list_deployments", "list_projects", "get_deployment"],
        "https://vercel.com/docs/rest-api",
    ),
    Entry(
        "netlify",
        "Netlify",
        "cloud",
        "Netlify sites + deploys",
        "bearer_token",
        ["NETLIFY_TOKEN"],
        ["list_sites", "list_deploys", "get_site"],
        "https://docs.netlify.com/api/get-started/",
    ),
    Entry(
        "render",
        "Render",
        "cloud",
        "Render services + deploys",
        "bearer_token",
        ["RENDER_API_KEY"],
        ["list_services", "get_service", "list_deploys"],
        "https://api-docs.render.com/",
    ),
    Entry(
        "fly-io",
        "Fly.io",
        "cloud",
        "Fly.io apps + machines",
        "bearer_token",
        ["FLY_API_TOKEN"],
        ["list_apps", "list_machines", "get_machine"],
        "https://fly.io/docs/machines/api/",
    ),
    Entry(
        "railway",
        "Railway",
        "cloud",
        "Railway projects + services",
        "bearer_token",
        ["RAILWAY_TOKEN"],
        ["list_projects", "list_services"],
        "https://docs.railway.app/reference/public-api",
    ),
    Entry(
        "heroku",
        "Heroku",
        "cloud",
        "Heroku apps + dynos",
        "bearer_token",
        ["HEROKU_API_KEY"],
        ["list_apps", "list_dynos"],
        "https://devcenter.heroku.com/articles/platform-api-reference",
    ),
    Entry(
        "oracle-cloud",
        "Oracle Cloud",
        "cloud",
        "OCI compute + storage",
        "custom",
        ["OCI_CONFIG_PROFILE"],
        ["list_instances", "list_buckets"],
        "https://docs.oracle.com/en-us/iaas/api/",
    ),
    Entry(
        "ibm-cloud",
        "IBM Cloud",
        "cloud",
        "IBM Cloud resources",
        "bearer_token",
        ["IBM_CLOUD_API_KEY"],
        ["list_resources"],
        "https://cloud.ibm.com/apidocs",
    ),
    # === DevOps / Infra (15) ===
    Entry(
        "kubernetes",
        "Kubernetes",
        "devops",
        "kubectl-equivalent operations",
        "custom",
        ["KUBECONFIG"],
        ["get_pods", "get_services", "get_deployments", "describe_pod", "logs"],
        "https://kubernetes.io/docs/reference/kubernetes-api/",
    ),
    Entry(
        "docker",
        "Docker",
        "devops",
        "Local Docker daemon operations",
        "custom",
        ["DOCKER_HOST"],
        ["list_containers", "list_images", "inspect_container", "logs"],
        "https://docs.docker.com/engine/api/",
    ),
    Entry(
        "terraform",
        "Terraform",
        "devops",
        "Terraform Cloud/Enterprise API",
        "bearer_token",
        ["TFC_TOKEN"],
        ["list_workspaces", "list_runs", "trigger_run"],
        "https://developer.hashicorp.com/terraform/cloud-docs/api-docs",
    ),
    Entry(
        "ansible",
        "Ansible",
        "devops",
        "Ansible AWX/Automation Platform",
        "bearer_token",
        ["AWX_TOKEN", "AWX_URL"],
        ["list_jobs", "launch_job"],
        "https://docs.ansible.com/automation-controller/latest/html/controllerapi/",
    ),
    Entry(
        "pulumi",
        "Pulumi",
        "devops",
        "Pulumi Cloud stacks",
        "bearer_token",
        ["PULUMI_ACCESS_TOKEN"],
        ["list_stacks", "list_updates"],
        "https://www.pulumi.com/docs/reference/service-rest-api/",
    ),
    Entry(
        "helm",
        "Helm",
        "devops",
        "Helm chart + release operations",
        "custom",
        ["KUBECONFIG"],
        ["list_releases", "get_release", "install", "upgrade"],
        "https://helm.sh/docs/",
    ),
    Entry(
        "argocd",
        "ArgoCD",
        "devops",
        "ArgoCD applications",
        "bearer_token",
        ["ARGOCD_TOKEN", "ARGOCD_URL"],
        ["list_applications", "sync_application"],
        "https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/",
    ),
    Entry(
        "jenkins",
        "Jenkins",
        "devops",
        "Jenkins jobs + builds",
        "basic",
        ["JENKINS_URL", "JENKINS_USER", "JENKINS_TOKEN"],
        ["list_jobs", "trigger_build", "get_build"],
        "https://www.jenkins.io/doc/book/using/remote-access-api/",
    ),
    Entry(
        "github-actions",
        "GitHub Actions",
        "devops",
        "GitHub Actions workflows",
        "bearer_token",
        ["GITHUB_TOKEN"],
        ["list_workflows", "list_runs", "trigger_workflow"],
        "https://docs.github.com/en/rest/actions",
    ),
    Entry(
        "gitlab-ci",
        "GitLab CI",
        "devops",
        "GitLab pipelines + jobs",
        "bearer_token",
        ["GITLAB_TOKEN"],
        ["list_pipelines", "trigger_pipeline"],
        "https://docs.gitlab.com/ee/api/pipelines.html",
    ),
    Entry(
        "circleci",
        "CircleCI",
        "devops",
        "CircleCI pipelines",
        "bearer_token",
        ["CIRCLECI_TOKEN"],
        ["list_projects", "list_workflows"],
        "https://circleci.com/docs/api/v2/",
    ),
    Entry(
        "buildkite",
        "Buildkite",
        "devops",
        "Buildkite pipelines",
        "bearer_token",
        ["BUILDKITE_TOKEN"],
        ["list_pipelines", "list_builds"],
        "https://buildkite.com/docs/apis/rest-api",
    ),
    Entry(
        "teamcity",
        "TeamCity",
        "devops",
        "JetBrains TeamCity API",
        "bearer_token",
        ["TEAMCITY_URL", "TEAMCITY_TOKEN"],
        ["list_projects", "trigger_build"],
        "https://www.jetbrains.com/help/teamcity/rest/teamcity-rest-api-documentation.html",
    ),
    Entry(
        "drone",
        "Drone CI",
        "devops",
        "Drone CI builds",
        "bearer_token",
        ["DRONE_TOKEN", "DRONE_SERVER"],
        ["list_repos", "list_builds"],
        "https://docs.drone.io/api/",
    ),
    Entry(
        "spinnaker",
        "Spinnaker",
        "devops",
        "Spinnaker pipelines",
        "custom",
        ["SPINNAKER_URL"],
        ["list_pipelines", "trigger_pipeline"],
        "https://spinnaker.io/docs/reference/api/",
    ),
    # === Communication (10) ===
    Entry(
        "slack",
        "Slack",
        "communication",
        "Slack Web API (channels, messages, users)",
        "bearer_token",
        ["SLACK_BOT_TOKEN"],
        ["list_channels", "post_message", "list_users", "get_conversation"],
        "https://api.slack.com/",
    ),
    Entry(
        "discord",
        "Discord",
        "communication",
        "Discord bot API",
        "bearer_token",
        ["DISCORD_BOT_TOKEN"],
        ["list_guilds", "list_channels", "post_message"],
        "https://discord.com/developers/docs/intro",
    ),
    Entry(
        "microsoft-teams",
        "Microsoft Teams",
        "communication",
        "MS Teams via Graph API",
        "bearer_token",
        ["MS_GRAPH_TOKEN"],
        ["list_teams", "list_channels", "post_message"],
        "https://learn.microsoft.com/en-us/graph/teams-concept-overview",
    ),
    Entry(
        "mattermost",
        "Mattermost",
        "communication",
        "Mattermost REST API",
        "bearer_token",
        ["MATTERMOST_URL", "MATTERMOST_TOKEN"],
        ["list_channels", "post_message"],
        "https://api.mattermost.com/",
    ),
    Entry(
        "rocket-chat",
        "Rocket.Chat",
        "communication",
        "Rocket.Chat REST API",
        "custom",
        ["ROCKETCHAT_URL", "ROCKETCHAT_TOKEN", "ROCKETCHAT_USER_ID"],
        ["list_channels", "post_message"],
        "https://developer.rocket.chat/reference/api",
    ),
    Entry(
        "telegram",
        "Telegram",
        "communication",
        "Telegram Bot API",
        "bearer_token",
        ["TELEGRAM_BOT_TOKEN"],
        ["send_message", "get_updates"],
        "https://core.telegram.org/bots/api",
    ),
    Entry(
        "whatsapp",
        "WhatsApp Business",
        "communication",
        "WhatsApp Cloud API",
        "bearer_token",
        ["WHATSAPP_TOKEN", "WHATSAPP_PHONE_ID"],
        ["send_message", "send_template"],
        "https://developers.facebook.com/docs/whatsapp/cloud-api",
    ),
    Entry(
        "twilio",
        "Twilio",
        "communication",
        "Twilio SMS/voice",
        "basic",
        ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
        ["send_sms", "list_messages", "make_call"],
        "https://www.twilio.com/docs/usage/api",
    ),
    Entry(
        "sendgrid",
        "SendGrid",
        "communication",
        "SendGrid email",
        "bearer_token",
        ["SENDGRID_API_KEY"],
        ["send_email", "list_templates"],
        "https://docs.sendgrid.com/api-reference",
    ),
    Entry(
        "mailgun",
        "Mailgun",
        "communication",
        "Mailgun email",
        "basic",
        ["MAILGUN_API_KEY", "MAILGUN_DOMAIN"],
        ["send_email", "list_events"],
        "https://documentation.mailgun.com/en/latest/api_reference.html",
    ),
    # === Project Management (10) ===
    Entry(
        "jira",
        "Jira",
        "project-management",
        "Atlassian Jira Cloud",
        "basic",
        ["JIRA_URL", "JIRA_USER", "JIRA_TOKEN"],
        ["search_issues", "get_issue", "create_issue", "update_issue", "list_projects"],
        "https://developer.atlassian.com/cloud/jira/platform/rest/v3/",
    ),
    Entry(
        "linear",
        "Linear",
        "project-management",
        "Linear GraphQL API",
        "bearer_token",
        ["LINEAR_API_KEY"],
        ["list_issues", "create_issue", "list_teams", "list_projects"],
        "https://developers.linear.app/docs",
    ),
    Entry(
        "asana",
        "Asana",
        "project-management",
        "Asana REST API",
        "bearer_token",
        ["ASANA_TOKEN"],
        ["list_workspaces", "list_projects", "list_tasks", "create_task"],
        "https://developers.asana.com/reference/rest-api-reference",
    ),
    Entry(
        "trello",
        "Trello",
        "project-management",
        "Trello REST API",
        "custom",
        ["TRELLO_KEY", "TRELLO_TOKEN"],
        ["list_boards", "list_cards", "create_card"],
        "https://developer.atlassian.com/cloud/trello/rest/",
    ),
    Entry(
        "clickup",
        "ClickUp",
        "project-management",
        "ClickUp API v2",
        "bearer_token",
        ["CLICKUP_TOKEN"],
        ["list_teams", "list_tasks", "create_task"],
        "https://clickup.com/api",
    ),
    Entry(
        "monday",
        "monday.com",
        "project-management",
        "monday.com GraphQL",
        "bearer_token",
        ["MONDAY_TOKEN"],
        ["list_boards", "list_items", "create_item"],
        "https://developer.monday.com/api-reference",
    ),
    Entry(
        "basecamp",
        "Basecamp",
        "project-management",
        "Basecamp 3+",
        "bearer_token",
        ["BASECAMP_TOKEN", "BASECAMP_ACCOUNT_ID"],
        ["list_projects", "list_todos", "create_todo"],
        "https://github.com/basecamp/bc3-api",
    ),
    Entry(
        "shortcut",
        "Shortcut",
        "project-management",
        "Shortcut REST API",
        "bearer_token",
        ["SHORTCUT_TOKEN"],
        ["list_stories", "create_story"],
        "https://developer.shortcut.com/api/rest/v3",
    ),
    Entry(
        "wrike",
        "Wrike",
        "project-management",
        "Wrike REST API",
        "bearer_token",
        ["WRIKE_TOKEN"],
        ["list_tasks", "create_task"],
        "https://developers.wrike.com/",
    ),
    Entry(
        "plane",
        "Plane",
        "project-management",
        "Plane open-source PM",
        "bearer_token",
        ["PLANE_URL", "PLANE_TOKEN"],
        ["list_projects", "list_issues", "create_issue"],
        "https://developers.plane.so/",
    ),
    # === Productivity / Notes (10) ===
    Entry(
        "notion",
        "Notion",
        "productivity",
        "Notion pages + databases",
        "bearer_token",
        ["NOTION_TOKEN"],
        ["search", "get_page", "create_page", "query_database"],
        "https://developers.notion.com/reference/intro",
    ),
    Entry(
        "confluence",
        "Confluence",
        "productivity",
        "Atlassian Confluence Cloud",
        "basic",
        ["CONFLUENCE_URL", "CONFLUENCE_USER", "CONFLUENCE_TOKEN"],
        ["list_spaces", "get_page", "search_content"],
        "https://developer.atlassian.com/cloud/confluence/rest/v2/",
    ),
    Entry(
        "obsidian",
        "Obsidian (local)",
        "productivity",
        "Local Obsidian vault access",
        "none",
        ["OBSIDIAN_VAULT_PATH"],
        ["list_notes", "read_note", "write_note", "search"],
        "https://help.obsidian.md/",
    ),
    Entry(
        "evernote",
        "Evernote",
        "productivity",
        "Evernote notes",
        "bearer_token",
        ["EVERNOTE_TOKEN"],
        ["list_notebooks", "list_notes"],
        "https://dev.evernote.com/",
    ),
    Entry(
        "onenote",
        "OneNote",
        "productivity",
        "OneNote via MS Graph",
        "bearer_token",
        ["MS_GRAPH_TOKEN"],
        ["list_notebooks", "list_pages"],
        "https://learn.microsoft.com/en-us/graph/api/resources/onenote-api-overview",
    ),
    Entry(
        "logseq",
        "Logseq",
        "productivity",
        "Local Logseq graph",
        "none",
        ["LOGSEQ_GRAPH_PATH"],
        ["list_pages", "read_page", "search"],
        "https://docs.logseq.com/",
    ),
    Entry(
        "roam",
        "Roam Research",
        "productivity",
        "Roam Research API",
        "bearer_token",
        ["ROAM_TOKEN", "ROAM_GRAPH"],
        ["list_pages", "query_block"],
        "https://roamresearch.com/#/app/developer-documentation",
    ),
    Entry(
        "anytype",
        "Anytype",
        "productivity",
        "Anytype local API",
        "custom",
        ["ANYTYPE_URL"],
        ["list_objects"],
        "https://developers.anytype.io/",
    ),
    Entry(
        "bear",
        "Bear (local)",
        "productivity",
        "Bear notes via SQLite",
        "none",
        ["BEAR_DB_PATH"],
        ["search", "read_note"],
        "https://bear.app/faq/",
    ),
    Entry(
        "dropbox-paper",
        "Dropbox Paper",
        "productivity",
        "Dropbox Paper docs",
        "bearer_token",
        ["DROPBOX_TOKEN"],
        ["list_docs", "get_doc"],
        "https://www.dropbox.com/developers/documentation/http/documentation",
    ),
    # === Storage / Files (10) ===
    Entry(
        "google-drive",
        "Google Drive",
        "storage",
        "Google Drive files",
        "gcp_sa",
        ["GOOGLE_APPLICATION_CREDENTIALS"],
        ["list_files", "get_file", "upload_file", "download_file"],
        "https://developers.google.com/drive/api",
    ),
    Entry(
        "onedrive",
        "OneDrive",
        "storage",
        "OneDrive via MS Graph",
        "bearer_token",
        ["MS_GRAPH_TOKEN"],
        ["list_files", "download_file"],
        "https://learn.microsoft.com/en-us/onedrive/developer/rest-api/",
    ),
    Entry(
        "dropbox",
        "Dropbox",
        "storage",
        "Dropbox file operations",
        "bearer_token",
        ["DROPBOX_TOKEN"],
        ["list_folder", "upload", "download"],
        "https://www.dropbox.com/developers/documentation",
    ),
    Entry(
        "box",
        "Box",
        "storage",
        "Box file operations",
        "bearer_token",
        ["BOX_TOKEN"],
        ["list_folder", "upload", "download"],
        "https://developer.box.com/reference/",
    ),
    Entry(
        "s3",
        "AWS S3",
        "storage",
        "S3 object storage",
        "aws_sig",
        ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
        ["list_buckets", "list_objects", "get_object", "put_object"],
        "https://docs.aws.amazon.com/s3/",
    ),
    Entry(
        "gcs",
        "Google Cloud Storage",
        "storage",
        "GCS bucket operations",
        "gcp_sa",
        ["GOOGLE_APPLICATION_CREDENTIALS"],
        ["list_buckets", "list_objects", "get_object", "upload_object"],
        "https://cloud.google.com/storage/docs",
    ),
    Entry(
        "azure-blob",
        "Azure Blob Storage",
        "storage",
        "Azure Blob operations",
        "custom",
        ["AZURE_STORAGE_CONNECTION_STRING"],
        ["list_containers", "list_blobs", "get_blob", "upload_blob"],
        "https://learn.microsoft.com/en-us/azure/storage/blobs/",
    ),
    Entry(
        "backblaze",
        "Backblaze B2",
        "storage",
        "Backblaze B2 (S3-compatible)",
        "custom",
        ["B2_KEY_ID", "B2_APPLICATION_KEY"],
        ["list_buckets", "list_files"],
        "https://www.backblaze.com/apidocs",
    ),
    Entry(
        "minio",
        "MinIO",
        "storage",
        "Self-hosted S3-compatible MinIO",
        "custom",
        ["MINIO_ENDPOINT", "MINIO_ACCESS_KEY", "MINIO_SECRET_KEY"],
        ["list_buckets", "list_objects", "get_object", "put_object"],
        "https://min.io/docs/",
    ),
    Entry(
        "filesystem",
        "Filesystem (local)",
        "storage",
        "Sandboxed local filesystem",
        "none",
        ["FS_ROOT"],
        ["read_file", "write_file", "list_dir", "stat", "search"],
        "https://modelcontextprotocol.io/",
        "pilot",
    ),
    # === Search / Web (10) ===
    Entry(
        "brave-search",
        "Brave Search",
        "search",
        "Brave Search API",
        "api_key",
        ["BRAVE_API_KEY"],
        ["web_search", "news_search"],
        "https://brave.com/search/api/",
    ),
    Entry(
        "google-search",
        "Google Custom Search",
        "search",
        "Google Programmable Search",
        "api_key",
        ["GOOGLE_CSE_KEY", "GOOGLE_CSE_ID"],
        ["search"],
        "https://developers.google.com/custom-search/v1/introduction",
    ),
    Entry(
        "bing-search",
        "Bing Search",
        "search",
        "Bing Web Search API",
        "api_key",
        ["BING_API_KEY"],
        ["web_search", "news_search"],
        "https://learn.microsoft.com/en-us/bing/search-apis/",
    ),
    Entry(
        "duckduckgo",
        "DuckDuckGo",
        "search",
        "DuckDuckGo instant answers",
        "none",
        [],
        ["search"],
        "https://duckduckgo.com/api",
    ),
    Entry(
        "tavily",
        "Tavily",
        "search",
        "Tavily search for LLMs",
        "api_key",
        ["TAVILY_API_KEY"],
        ["search", "extract"],
        "https://docs.tavily.com/",
    ),
    Entry(
        "perplexity",
        "Perplexity",
        "search",
        "Perplexity online API",
        "bearer_token",
        ["PERPLEXITY_API_KEY"],
        ["ask"],
        "https://docs.perplexity.ai/",
    ),
    Entry(
        "exa",
        "Exa",
        "search",
        "Exa neural search",
        "api_key",
        ["EXA_API_KEY"],
        ["search", "find_similar", "contents"],
        "https://docs.exa.ai/",
    ),
    Entry(
        "serpapi",
        "SerpAPI",
        "search",
        "SerpAPI SERP scraping",
        "api_key",
        ["SERPAPI_KEY"],
        ["search"],
        "https://serpapi.com/search-api",
    ),
    Entry(
        "firecrawl",
        "Firecrawl",
        "search",
        "Firecrawl web scraping",
        "bearer_token",
        ["FIRECRAWL_API_KEY"],
        ["crawl", "scrape", "map"],
        "https://docs.firecrawl.dev/",
    ),
    Entry(
        "jina",
        "Jina Reader",
        "search",
        "Jina Reader web-to-markdown",
        "bearer_token",
        ["JINA_API_KEY"],
        ["read_url", "search"],
        "https://jina.ai/reader/",
    ),
    # === Browser / Automation (5) ===
    Entry(
        "playwright",
        "Playwright",
        "browser",
        "Playwright browser automation",
        "none",
        [],
        ["navigate", "click", "fill", "screenshot", "extract_text"],
        "https://playwright.dev/python/",
    ),
    Entry(
        "puppeteer",
        "Puppeteer",
        "browser",
        "Puppeteer via Node bridge",
        "none",
        [],
        ["navigate", "click", "screenshot"],
        "https://pptr.dev/",
    ),
    Entry(
        "selenium",
        "Selenium",
        "browser",
        "Selenium WebDriver",
        "none",
        [],
        ["navigate", "click", "screenshot"],
        "https://www.selenium.dev/documentation/",
    ),
    Entry(
        "browserbase",
        "Browserbase",
        "browser",
        "Browserbase cloud browsers",
        "bearer_token",
        ["BROWSERBASE_API_KEY", "BROWSERBASE_PROJECT_ID"],
        ["create_session", "navigate", "screenshot"],
        "https://docs.browserbase.com/",
    ),
    Entry(
        "chrome-devtools",
        "Chrome DevTools",
        "browser",
        "CDP protocol operations",
        "none",
        ["CHROME_DEBUG_URL"],
        ["navigate", "evaluate", "screenshot"],
        "https://chromedevtools.github.io/devtools-protocol/",
    ),
    # === Monitoring / Observability (10) ===
    Entry(
        "datadog",
        "Datadog",
        "monitoring",
        "Datadog metrics + logs + monitors",
        "custom",
        ["DATADOG_API_KEY", "DATADOG_APP_KEY", "DATADOG_SITE"],
        ["query_metric", "list_monitors", "search_logs"],
        "https://docs.datadoghq.com/api/latest/",
    ),
    Entry(
        "new-relic",
        "New Relic",
        "monitoring",
        "New Relic NRQL + entities",
        "custom",
        ["NEWRELIC_API_KEY", "NEWRELIC_ACCOUNT"],
        ["nrql", "list_alerts"],
        "https://docs.newrelic.com/docs/apis/",
    ),
    Entry(
        "sentry",
        "Sentry",
        "monitoring",
        "Sentry issues + events",
        "bearer_token",
        ["SENTRY_TOKEN", "SENTRY_ORG"],
        ["list_issues", "get_issue", "list_events"],
        "https://docs.sentry.io/api/",
    ),
    Entry(
        "grafana",
        "Grafana",
        "monitoring",
        "Grafana dashboards + queries",
        "bearer_token",
        ["GRAFANA_URL", "GRAFANA_TOKEN"],
        ["list_dashboards", "query_datasource"],
        "https://grafana.com/docs/grafana/latest/developers/http_api/",
    ),
    Entry(
        "prometheus",
        "Prometheus",
        "monitoring",
        "Prometheus PromQL queries",
        "custom",
        ["PROMETHEUS_URL"],
        ["query", "query_range", "list_targets"],
        "https://prometheus.io/docs/prometheus/latest/querying/api/",
    ),
    Entry(
        "splunk",
        "Splunk",
        "monitoring",
        "Splunk search + reports",
        "bearer_token",
        ["SPLUNK_URL", "SPLUNK_TOKEN"],
        ["search", "list_saved_searches"],
        "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog",
    ),
    Entry(
        "loki",
        "Grafana Loki",
        "monitoring",
        "Loki log queries",
        "custom",
        ["LOKI_URL"],
        ["query", "query_range", "list_labels"],
        "https://grafana.com/docs/loki/latest/reference/api/",
    ),
    Entry(
        "jaeger",
        "Jaeger",
        "monitoring",
        "Jaeger tracing",
        "custom",
        ["JAEGER_URL"],
        ["list_services", "get_trace", "search_traces"],
        "https://www.jaegertracing.io/docs/latest/apis/",
    ),
    Entry(
        "honeycomb",
        "Honeycomb",
        "monitoring",
        "Honeycomb queries + boards",
        "custom",
        ["HONEYCOMB_API_KEY"],
        ["query_dataset", "list_boards"],
        "https://docs.honeycomb.io/api/",
    ),
    Entry(
        "pagerduty",
        "PagerDuty",
        "monitoring",
        "PagerDuty incidents + services",
        "bearer_token",
        ["PAGERDUTY_TOKEN"],
        ["list_incidents", "create_incident", "list_services"],
        "https://developer.pagerduty.com/api-reference/",
    ),
    # === Security (8) ===
    Entry(
        "vault",
        "HashiCorp Vault",
        "security",
        "Vault secret operations",
        "bearer_token",
        ["VAULT_ADDR", "VAULT_TOKEN"],
        ["read_secret", "write_secret", "list_secrets"],
        "https://developer.hashicorp.com/vault/api-docs",
    ),
    Entry(
        "1password",
        "1Password",
        "security",
        "1Password Connect",
        "bearer_token",
        ["OP_CONNECT_HOST", "OP_CONNECT_TOKEN"],
        ["list_vaults", "list_items", "get_item"],
        "https://developer.1password.com/docs/connect/",
    ),
    Entry(
        "bitwarden",
        "Bitwarden",
        "security",
        "Bitwarden vault via CLI",
        "custom",
        ["BW_SESSION"],
        ["list_items", "get_item"],
        "https://bitwarden.com/help/vault-management-api/",
    ),
    Entry(
        "lastpass",
        "LastPass",
        "security",
        "LastPass Enterprise API",
        "custom",
        ["LASTPASS_CID", "LASTPASS_API_HASH"],
        ["list_users"],
        "https://support.lastpass.com/help/use-the-lastpass-provisioning-api",
    ),
    Entry(
        "okta",
        "Okta",
        "security",
        "Okta users, groups, apps",
        "bearer_token",
        ["OKTA_URL", "OKTA_TOKEN"],
        ["list_users", "list_groups", "list_apps"],
        "https://developer.okta.com/docs/reference/",
    ),
    Entry(
        "auth0",
        "Auth0",
        "security",
        "Auth0 management API",
        "bearer_token",
        ["AUTH0_DOMAIN", "AUTH0_TOKEN"],
        ["list_users", "list_clients", "list_rules"],
        "https://auth0.com/docs/api/management/v2",
    ),
    Entry(
        "snyk",
        "Snyk",
        "security",
        "Snyk vulnerability scanning",
        "bearer_token",
        ["SNYK_TOKEN", "SNYK_ORG"],
        ["list_projects", "list_issues"],
        "https://docs.snyk.io/snyk-api",
    ),
    Entry(
        "semgrep",
        "Semgrep",
        "security",
        "Semgrep findings + rules",
        "bearer_token",
        ["SEMGREP_TOKEN"],
        ["list_findings", "list_rules"],
        "https://semgrep.dev/api/v1/docs/",
    ),
    # === AI / ML (10) ===
    Entry(
        "openai",
        "OpenAI",
        "ai-ml",
        "OpenAI chat + embeddings + images",
        "bearer_token",
        ["OPENAI_API_KEY"],
        ["chat_completion", "embed", "generate_image"],
        "https://platform.openai.com/docs/api-reference",
    ),
    Entry(
        "anthropic",
        "Anthropic",
        "ai-ml",
        "Anthropic Messages API",
        "api_key",
        ["ANTHROPIC_API_KEY"],
        ["messages"],
        "https://docs.anthropic.com/en/api",
    ),
    Entry(
        "huggingface",
        "Hugging Face",
        "ai-ml",
        "HF Hub + Inference",
        "bearer_token",
        ["HF_TOKEN"],
        ["list_models", "get_model", "whoami"],
        "https://huggingface.co/docs/api-inference/",
    ),
    Entry(
        "replicate",
        "Replicate",
        "ai-ml",
        "Replicate model runs",
        "bearer_token",
        ["REPLICATE_TOKEN"],
        ["run_model", "list_models"],
        "https://replicate.com/docs/reference/http",
    ),
    Entry(
        "openrouter",
        "OpenRouter",
        "ai-ml",
        "OpenRouter LLM gateway",
        "bearer_token",
        ["OPENROUTER_API_KEY"],
        ["chat_completion", "list_models"],
        "https://openrouter.ai/docs",
    ),
    Entry(
        "mistral",
        "Mistral",
        "ai-ml",
        "Mistral La Plateforme",
        "bearer_token",
        ["MISTRAL_API_KEY"],
        ["chat_completion", "embed"],
        "https://docs.mistral.ai/",
    ),
    Entry(
        "cohere",
        "Cohere",
        "ai-ml",
        "Cohere chat + embed + rerank",
        "bearer_token",
        ["COHERE_API_KEY"],
        ["chat", "embed", "rerank"],
        "https://docs.cohere.com/reference/about",
    ),
    Entry(
        "groq",
        "Groq",
        "ai-ml",
        "Groq inference",
        "bearer_token",
        ["GROQ_API_KEY"],
        ["chat_completion"],
        "https://console.groq.com/docs/quickstart",
    ),
    Entry(
        "together-ai",
        "Together AI",
        "ai-ml",
        "Together inference",
        "bearer_token",
        ["TOGETHER_API_KEY"],
        ["chat_completion", "embed"],
        "https://docs.together.ai/",
    ),
    Entry(
        "modal",
        "Modal",
        "ai-ml",
        "Modal serverless compute",
        "custom",
        ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
        ["list_apps", "invoke_function"],
        "https://modal.com/docs/reference",
    ),
    # === Data Platforms (8) ===
    Entry(
        "snowflake",
        "Snowflake",
        "data-platform",
        "Snowflake queries + warehouse",
        "custom",
        ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD"],
        ["query", "list_databases", "list_warehouses"],
        "https://docs.snowflake.com/",
    ),
    Entry(
        "databricks",
        "Databricks",
        "data-platform",
        "Databricks SQL + jobs",
        "bearer_token",
        ["DATABRICKS_HOST", "DATABRICKS_TOKEN"],
        ["run_sql", "list_jobs", "trigger_job"],
        "https://docs.databricks.com/api/",
    ),
    Entry(
        "bigquery",
        "BigQuery",
        "data-platform",
        "BigQuery SQL",
        "gcp_sa",
        ["GOOGLE_APPLICATION_CREDENTIALS", "GCP_PROJECT"],
        ["query", "list_datasets", "list_tables"],
        "https://cloud.google.com/bigquery/docs",
    ),
    Entry(
        "redshift",
        "Redshift",
        "data-platform",
        "AWS Redshift",
        "custom",
        ["REDSHIFT_DSN"],
        ["query", "list_tables"],
        "https://docs.aws.amazon.com/redshift/",
    ),
    Entry(
        "dbt",
        "dbt Cloud",
        "data-platform",
        "dbt Cloud jobs + runs",
        "bearer_token",
        ["DBT_TOKEN", "DBT_ACCOUNT_ID"],
        ["list_jobs", "trigger_job", "list_runs"],
        "https://docs.getdbt.com/dbt-cloud/api-v2-legacy",
    ),
    Entry(
        "airbyte",
        "Airbyte",
        "data-platform",
        "Airbyte connections + jobs",
        "bearer_token",
        ["AIRBYTE_URL", "AIRBYTE_TOKEN"],
        ["list_connections", "trigger_sync"],
        "https://docs.airbyte.com/api-documentation",
    ),
    Entry(
        "fivetran",
        "Fivetran",
        "data-platform",
        "Fivetran connectors",
        "basic",
        ["FIVETRAN_API_KEY", "FIVETRAN_API_SECRET"],
        ["list_connectors", "sync_connector"],
        "https://fivetran.com/docs/rest-api",
    ),
    Entry(
        "airflow",
        "Airflow",
        "data-platform",
        "Airflow DAGs + runs",
        "basic",
        ["AIRFLOW_URL", "AIRFLOW_USER", "AIRFLOW_PASSWORD"],
        ["list_dags", "trigger_dag", "list_runs"],
        "https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html",
    ),
    # === Business / CRM (10) ===
    Entry(
        "salesforce",
        "Salesforce",
        "business",
        "Salesforce SOQL + REST",
        "bearer_token",
        ["SALESFORCE_URL", "SALESFORCE_TOKEN"],
        ["soql", "get_record", "create_record", "update_record"],
        "https://developer.salesforce.com/docs/apis",
    ),
    Entry(
        "hubspot",
        "HubSpot",
        "business",
        "HubSpot CRM",
        "bearer_token",
        ["HUBSPOT_TOKEN"],
        ["list_contacts", "list_deals", "list_companies"],
        "https://developers.hubspot.com/docs/api/overview",
    ),
    Entry(
        "stripe",
        "Stripe",
        "business",
        "Stripe payments + customers",
        "bearer_token",
        ["STRIPE_SECRET_KEY"],
        ["list_customers", "list_charges", "list_subscriptions", "create_payment_intent"],
        "https://stripe.com/docs/api",
    ),
    Entry(
        "shopify",
        "Shopify",
        "business",
        "Shopify Admin API",
        "bearer_token",
        ["SHOPIFY_STORE", "SHOPIFY_TOKEN"],
        ["list_products", "list_orders", "list_customers"],
        "https://shopify.dev/docs/api",
    ),
    Entry(
        "woocommerce",
        "WooCommerce",
        "business",
        "WooCommerce REST",
        "basic",
        ["WOO_URL", "WOO_KEY", "WOO_SECRET"],
        ["list_products", "list_orders"],
        "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    ),
    Entry(
        "quickbooks",
        "QuickBooks",
        "business",
        "QuickBooks Online",
        "bearer_token",
        ["QB_TOKEN", "QB_REALM_ID"],
        ["list_invoices", "list_customers"],
        "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account",
    ),
    Entry(
        "zendesk",
        "Zendesk",
        "business",
        "Zendesk Support",
        "basic",
        ["ZENDESK_URL", "ZENDESK_EMAIL", "ZENDESK_TOKEN"],
        ["list_tickets", "create_ticket", "list_users"],
        "https://developer.zendesk.com/api-reference/",
    ),
    Entry(
        "intercom",
        "Intercom",
        "business",
        "Intercom conversations + contacts",
        "bearer_token",
        ["INTERCOM_TOKEN"],
        ["list_conversations", "list_contacts"],
        "https://developers.intercom.com/docs/references/rest-api",
    ),
    Entry(
        "freshdesk",
        "Freshdesk",
        "business",
        "Freshdesk tickets",
        "basic",
        ["FRESHDESK_URL", "FRESHDESK_API_KEY"],
        ["list_tickets", "create_ticket"],
        "https://developers.freshdesk.com/api/",
    ),
    Entry(
        "mailchimp",
        "Mailchimp",
        "business",
        "Mailchimp audiences + campaigns",
        "basic",
        ["MAILCHIMP_API_KEY", "MAILCHIMP_SERVER"],
        ["list_audiences", "list_campaigns", "add_subscriber"],
        "https://mailchimp.com/developer/marketing/api/",
    ),
    # === Utilities (10) ===
    Entry(
        "fetch",
        "Fetch (HTTP)",
        "utility",
        "HTTP fetch + markdown extraction",
        "none",
        [],
        ["fetch", "fetch_markdown"],
        "https://modelcontextprotocol.io/",
        "pilot",
    ),
    Entry(
        "time",
        "Time",
        "utility",
        "Time zone conversions + current time",
        "none",
        [],
        ["now", "convert_timezone", "format", "parse"],
        "https://docs.python.org/3/library/zoneinfo.html",
        "pilot",
    ),
    Entry(
        "weather",
        "Weather",
        "utility",
        "OpenWeatherMap current + forecast",
        "api_key",
        ["OPENWEATHER_API_KEY"],
        ["current", "forecast"],
        "https://openweathermap.org/api",
    ),
    Entry(
        "calculator",
        "Calculator",
        "utility",
        "Safe arithmetic evaluator",
        "none",
        [],
        ["eval", "solve"],
        "https://docs.python.org/3/library/math.html",
    ),
    Entry(
        "shell",
        "Shell",
        "utility",
        "Sandboxed shell command execution",
        "none",
        ["SHELL_ALLOWLIST"],
        ["run_command"],
        "https://man7.org/linux/man-pages/",
    ),
    Entry(
        "ssh",
        "SSH",
        "utility",
        "SSH remote command execution",
        "custom",
        ["SSH_HOST", "SSH_USER", "SSH_KEY_PATH"],
        ["run_command", "put_file", "get_file"],
        "https://www.openssh.com/manual.html",
    ),
    Entry(
        "rss",
        "RSS",
        "utility",
        "RSS/Atom feed reader",
        "none",
        [],
        ["fetch_feed", "list_entries"],
        "https://feedparser.readthedocs.io/",
    ),
    Entry(
        "wikipedia",
        "Wikipedia",
        "utility",
        "Wikipedia search + article fetch",
        "none",
        [],
        ["search", "get_article", "get_summary"],
        "https://www.mediawiki.org/wiki/API:Main_page",
    ),
    Entry(
        "arxiv",
        "arXiv",
        "utility",
        "arXiv paper search + metadata",
        "none",
        [],
        ["search", "get_paper"],
        "https://arxiv.org/help/api",
    ),
    Entry(
        "pdf",
        "PDF",
        "utility",
        "PDF text extraction + metadata",
        "none",
        [],
        ["extract_text", "extract_metadata", "extract_pages"],
        "https://pymupdf.readthedocs.io/",
    ),
    Entry(
        "airtable",
        "Airtable",
        "productivity",
        "Airtable base + record operations",
        "bearer_token",
        ["AIRTABLE_TOKEN"],
        ["list_bases", "list_tables", "list_records", "create_record", "update_record"],
        "https://airtable.com/developers/web/api/introduction",
    ),
    Entry(
        "gemini",
        "Google Gemini",
        "ai-ml",
        "Google Gemini generative model API",
        "api_key",
        ["GEMINI_API_KEY"],
        ["generate_content", "embed_content", "list_models"],
        "https://ai.google.dev/api/rest",
    ),
    Entry(
        "wordpress",
        "WordPress",
        "productivity",
        "WordPress REST API",
        "basic",
        ["WP_URL", "WP_USER", "WP_PASSWORD"],
        ["list_posts", "create_post", "list_pages"],
        "https://developer.wordpress.org/rest-api/",
    ),
    Entry(
        "google-analytics",
        "Google Analytics",
        "monitoring",
        "GA4 Data API",
        "bearer_token",
        ["GA_TOKEN", "GA_PROPERTY_ID"],
        ["run_report", "list_dimensions", "list_metrics"],
        "https://developers.google.com/analytics/devguides/reporting/data/v1",
    ),
]


# Port assignment: 8000 = gateway, 8001-8171 = servers in catalogue order.
def assign_ports() -> dict[str, int]:
    return {entry.id: 8001 + i for i, entry in enumerate(CATALOGUE)}


def to_manifest(entry: Entry, port: int) -> dict:
    return {
        "id": entry.id,
        "name": entry.name,
        "category": entry.category,
        "description": entry.description,
        "auth": {
            "type": entry.auth_type,
            "env": entry.auth_env,
        },
        "transport": "streamable-http",
        "port": port,
        "image": f"yourorg/mcp-{entry.id}",
        "version": "0.1.0",
        "tools": entry.tools,
        "docs": entry.docs,
        "maintainers": ["platform-team"],
        "status": _preserve_status(entry.id, entry.status),
    }


def _preserve_status(server_id: str, default: str = "planned") -> str:
    """Return the current status: value from the existing yaml, else `default`."""
    from pathlib import Path as _Path

    p = _Path(__file__).resolve().parent.parent / "registry" / "servers" / f"{server_id}.yaml"
    if not p.exists():
        return default
    for line in p.read_text().splitlines():
        s = line.strip()
        if s.startswith("status:"):
            return s.split(":", 1)[1].strip()
    return default


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ports = assign_ports()

    seen_ids: set[str] = set()
    seen_ports: set[int] = set()

    for entry in CATALOGUE:
        if entry.id in seen_ids:
            raise ValueError(f"Duplicate id: {entry.id}")
        seen_ids.add(entry.id)

        port = ports[entry.id]
        if port in seen_ports:
            raise ValueError(f"Duplicate port {port} for {entry.id}")
        seen_ports.add(port)

        manifest = to_manifest(entry, port)
        out_path = OUT_DIR / f"{entry.id}.yaml"
        with out_path.open("w") as f:
            yaml.safe_dump(manifest, f, sort_keys=False, default_flow_style=False)

    index = {
        "count": len(CATALOGUE),
        "categories": sorted({e.category for e in CATALOGUE}),
        "servers": [
            {"id": e.id, "category": e.category, "port": ports[e.id], "status": e.status}
            for e in CATALOGUE
        ],
    }
    with (REPO_ROOT / "registry" / "index.yaml").open("w") as f:
        yaml.safe_dump(index, f, sort_keys=False, default_flow_style=False)

    print(f"Wrote {len(CATALOGUE)} server manifests to {OUT_DIR}")
    print(f"Wrote index to {REPO_ROOT / 'registry' / 'index.yaml'}")


if __name__ == "__main__":
    main()
